//! Swift tree-sitter parsing helpers.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use wax_contract::{Diagnostic, DiagnosticSeverity, SourceLocation};

/// Parsed Swift file.
#[derive(Debug)]
#[allow(dead_code)]
pub(crate) struct ParsedSwiftFile {
    /// Parsed tree-sitter syntax tree.
    pub(crate) tree: tree_sitter::Tree,
    /// Source text used to parse the file.
    pub(crate) source: String,
}

/// Errors produced while parsing a Swift source file.
#[derive(Debug)]
pub(crate) enum ParseSwiftFileError {
    /// A filesystem operation failed.
    Io {
        /// Human-readable context.
        context: String,
        /// Underlying I/O error.
        source: std::io::Error,
    },
    /// Tree-sitter returned a tree containing syntax errors.
    ParseFailed(PathBuf),
}

impl std::fmt::Display for ParseSwiftFileError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io { context, source } => write!(f, "{context}: {source}"),
            Self::ParseFailed(path) => {
                write!(f, "failed to parse Swift source {}", path.display())
            }
        }
    }
}

impl std::error::Error for ParseSwiftFileError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::ParseFailed(_) => None,
        }
    }
}

/// Creates a tree-sitter parser configured for Swift.
pub(crate) fn new_parser() -> Result<tree_sitter::Parser, String> {
    let mut parser = tree_sitter::Parser::new();
    let language_fn = tree_sitter_swift::LANGUAGE.into_raw();
    let language_ptr = unsafe { language_fn() };
    // SAFETY: `tree_sitter_swift::LANGUAGE` is generated by tree-sitter and returns
    // a valid `TSLanguage` pointer for the linked grammar.
    let language = unsafe {
        tree_sitter::Language::from_raw(language_ptr as *const tree_sitter::ffi::TSLanguage)
    };
    parser
        .set_language(&language)
        .map_err(|err| err.to_string())?;
    Ok(parser)
}

/// Recursively collects Swift source files under `dir`.
pub(crate) fn collect_swift_files(
    dir: &Path,
    files: &mut Vec<PathBuf>,
) -> Result<(), std::io::Error> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = fs::symlink_metadata(&path)?.file_type();
        if file_type.is_symlink() {
            continue;
        }
        if file_type.is_dir() {
            collect_swift_files(&path, files)?;
        } else if file_type.is_file()
            && path.extension().and_then(|ext| ext.to_str()) == Some("swift")
        {
            files.push(path);
        }
    }
    Ok(())
}

/// Parses a Swift file and keeps partial trees when tree-sitter can recover.
///
/// Unlike strict parsing, recoverable syntax errors do not fail the parse. Callers
/// should extract symbols from the returned tree even when `tree.root_node().has_error()`.
pub(crate) fn parse_swift_file_permissive(
    parser: &mut tree_sitter::Parser,
    path: &Path,
) -> Result<ParsedSwiftFile, ParseSwiftFileError> {
    let source = fs::read_to_string(path).map_err(|source| ParseSwiftFileError::Io {
        context: format!("read Swift source {}", path.display()),
        source,
    })?;
    let tree = parser
        .parse(source.as_bytes(), None)
        .ok_or_else(|| ParseSwiftFileError::ParseFailed(path.to_path_buf()))?;

    Ok(ParsedSwiftFile { tree, source })
}

/// Parses a Swift file and fails on any syntax error.
#[allow(dead_code)]
pub(crate) fn parse_swift_file_strict(
    parser: &mut tree_sitter::Parser,
    path: &Path,
) -> Result<ParsedSwiftFile, ParseSwiftFileError> {
    let parsed = parse_swift_file_permissive(parser, path)?;
    if tree_has_syntax_errors(&parsed.tree) {
        return Err(ParseSwiftFileError::ParseFailed(path.to_path_buf()));
    }

    Ok(parsed)
}

/// Returns whether tree-sitter reported recoverable syntax errors in a parsed tree.
pub(crate) fn tree_has_syntax_errors(tree: &tree_sitter::Tree) -> bool {
    tree.root_node().has_error()
}

/// Diagnostic emitted when tree-sitter returns no syntax tree for a source file.
pub(crate) fn unparseable_file_diagnostic(relative_file: &str) -> Diagnostic {
    Diagnostic {
        severity: DiagnosticSeverity::Error,
        code: "parse_failed".to_owned(),
        message: format!("tree-sitter failed to parse {relative_file}; file skipped"),
        location: Some(SourceLocation {
            file: relative_file.to_owned(),
            line: 1,
            column: None,
        }),
    }
}

/// Diagnostic emitted when tree-sitter recovers a partial tree with syntax errors.
pub(crate) fn partial_tree_parse_diagnostic(
    root: tree_sitter::Node<'_>,
    relative_file: &str,
) -> Diagnostic {
    Diagnostic {
        severity: DiagnosticSeverity::Error,
        code: "parse_failed".to_owned(),
        message: format!(
            "tree-sitter reported syntax errors in {relative_file}; file scanned with gaps"
        ),
        location: first_syntax_error_location(root, relative_file),
    }
}

fn first_syntax_error_location(
    root: tree_sitter::Node<'_>,
    relative_file: &str,
) -> Option<SourceLocation> {
    let node = first_error_node(root)?;
    let start = node.start_position();
    Some(SourceLocation {
        file: relative_file.to_owned(),
        line: u32::try_from(start.row.saturating_add(1)).unwrap_or(u32::MAX),
        column: Some(u32::try_from(start.column.saturating_add(1)).unwrap_or(u32::MAX)),
    })
}

fn first_error_node(node: tree_sitter::Node<'_>) -> Option<tree_sitter::Node<'_>> {
    if node.is_error() || node.is_missing() {
        return Some(node);
    }

    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        if let Some(found) = first_error_node(child) {
            return Some(found);
        }
    }

    None
}

/// Import bindings collected from Swift `import` declarations in one source file.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) struct ImportBindings {
    /// Maps local symbol names to the module prefix they were imported from.
    pub symbol_packages: BTreeMap<String, String>,
    /// Module imports that expose all public symbols from a module.
    pub module_imports: Vec<String>,
}

impl ImportBindings {
    /// Returns the module prefix for a symbol used at a call site, when known.
    pub(crate) fn package_for_symbol(&self, symbol: &str) -> Option<String> {
        if let Some(package) = self.symbol_packages.get(symbol) {
            return Some(package.clone());
        }

        match self.module_imports.len() {
            0 => None,
            1 => Some(self.module_imports[0].clone()),
            _ => None,
        }
    }

    /// Returns the import package for a call site, preferring an explicit qualifier.
    pub(crate) fn package_for_call(&self, symbol: &str, qualifier: Option<&str>) -> Option<String> {
        if let Some(qualifier) = qualifier.filter(|value| !value.is_empty()) {
            return Some(qualifier.to_owned());
        }

        self.package_for_symbol(symbol)
    }
}

/// Collects import bindings from the top level of a Swift source file.
pub(crate) fn collect_import_bindings(
    root: tree_sitter::Node<'_>,
    source: &[u8],
) -> ImportBindings {
    let mut bindings = ImportBindings::default();
    let mut stack = vec![root];

    while let Some(node) = stack.pop() {
        if node.kind() == "import_declaration"
            && let Some(module_name) = import_module_from_declaration(node, source)
        {
            if let Some((package, symbol)) = module_name.rsplit_once('.') {
                if !package.is_empty() {
                    bindings
                        .symbol_packages
                        .insert(symbol.to_owned(), package.to_owned());
                }
            } else {
                bindings.module_imports.push(module_name);
            }
            continue;
        }

        for index in (0..node.child_count()).rev() {
            if let Some(child) = node.child(index) {
                stack.push(child);
            }
        }
    }

    bindings.module_imports.sort();
    bindings
}

fn import_module_from_declaration(
    import_node: tree_sitter::Node<'_>,
    source: &[u8],
) -> Option<String> {
    let mut cursor = import_node.walk();
    for child in import_node.named_children(&mut cursor) {
        if matches!(
            child.kind(),
            "identifier" | "simple_identifier" | "type_identifier"
        ) {
            return child.utf8_text(source).ok().map(str::to_owned);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn collect_import_bindings_tracks_module_and_selective_imports() {
        let mut parser = new_parser().expect("parser");
        let source = r#"
import SwiftUI
import AcmeDesignSystem
import struct Foundation.URL

struct Screen: View {
    var body: some View { Text("ok") }
}
"#;
        let tree = parser.parse(source.as_bytes(), None).expect("tree");
        let bindings = collect_import_bindings(tree.root_node(), source.as_bytes());

        assert_eq!(bindings.module_imports, vec!["AcmeDesignSystem", "SwiftUI"]);
        assert_eq!(
            bindings.symbol_packages.get("URL"),
            Some(&"Foundation".to_owned())
        );
        assert_eq!(bindings.package_for_symbol("Button"), None);
        assert_eq!(
            bindings.package_for_call("Button", Some("SwiftUI")),
            Some("SwiftUI".to_owned())
        );
        assert_eq!(
            bindings.package_for_call("Button", None),
            None,
            "unqualified calls stay ambiguous when multiple modules are imported"
        );

        let single_module_source = "import SwiftUI\nstruct Screen {}\n";
        let single_tree = parser
            .parse(single_module_source.as_bytes(), None)
            .expect("tree");
        let single_bindings =
            collect_import_bindings(single_tree.root_node(), single_module_source.as_bytes());
        assert_eq!(
            single_bindings.package_for_symbol("Button"),
            Some("SwiftUI".to_owned())
        );
    }

    #[test]
    fn collect_swift_files_recurses_and_skips_non_swift_files() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        fs::create_dir_all(tempdir.path().join("Sources/App")).unwrap();
        fs::write(
            tempdir.path().join("Sources/App/View.swift"),
            "struct View {}",
        )
        .unwrap();
        fs::write(tempdir.path().join("Sources/App/View.txt"), "not swift").unwrap();

        let mut files = Vec::new();
        collect_swift_files(&tempdir.path().join("Sources"), &mut files).unwrap();
        files.sort();

        assert_eq!(files.len(), 1);
        assert!(files[0].ends_with("View.swift"));
    }

    #[cfg(unix)]
    #[test]
    fn collect_swift_files_skips_non_regular_swift_paths() {
        use std::os::unix::net::UnixListener;

        let tempdir = tempfile::tempdir().expect("tempdir");
        fs::create_dir_all(tempdir.path().join("Sources/App")).unwrap();
        fs::write(
            tempdir.path().join("Sources/App/View.swift"),
            "struct View {}",
        )
        .unwrap();

        let socket_path = tempdir.path().join("Sources/App/Fake.swift");
        let _listener = UnixListener::bind(&socket_path).expect("bind unix socket");

        let mut files = Vec::new();
        collect_swift_files(&tempdir.path().join("Sources"), &mut files).unwrap();
        files.sort();

        assert_eq!(files.len(), 1);
        assert!(files[0].ends_with("View.swift"));
    }

    #[test]
    fn parse_swift_file_returns_tree_for_valid_source() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        fs::create_dir_all(tempdir.path().join("Sources")).unwrap();
        fs::write(
            tempdir.path().join("Sources/Card.swift"),
            "import SwiftUI\nstruct Card: View { var body: some View { Text(\"Card\") } }\n",
        )
        .unwrap();

        let mut parser = new_parser().expect("parser");
        let parsed =
            parse_swift_file_permissive(&mut parser, &tempdir.path().join("Sources/Card.swift"))
                .expect("parse");

        assert!(parsed.source.contains("struct Card"));
        assert!(!parsed.tree.root_node().has_error());
    }
}
